unstable_features = true
max_width = 80
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
binop_separator = "Back"
comment_width = 120
reorder_imports = true
tab_spaces = 4
trailing_semicolon = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
