[toolchain]
channel = "nightly"
profile = "minimal"
components = ["rustfmt", "clippy", "rust-src"]
targets = [
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
]
