name: Bug Report
description: |
    Use this template for **non-crash-related** bug reports.
labels: ["bug"]
body:
    - type: checkboxes
      attributes:
          label: Check for existing issues
          description:
              Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a
              `+1` (👍) on it.
          options:
              - label: Completed
                required: true
    - type: textarea
      attributes:
          label: Describe the bug / provide steps to reproduce it
          description: A clear and concise description of what the bug is.
      validations:
          required: true
    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: |
              - OS: [e.g. archlinux]
              - vterm Version: [e.g. 0.1.0]
      validations:
          required: true
    - type: textarea
      attributes:
          label: If applicable, add mockups / screenshots to help explain present your vision of the feature
          description: Drag issues into the text input below
      validations:
          required: false
    - type: textarea
      attributes:
          label: If applicable, attach any further logs or debug discoveries here.
          description: |
              We currently do not have proper logs, but will improve this in the future.
      validations:
          required: false
